package com.mockiq.backend.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * InterviewQuestion — one AI-generated question within a session.
 *
 * Generated by Gemini at session start (Phase 5, Step 3).
 * Stores the question text, expected answer outline,
 * category (TECHNICAL / BEHAVIOURAL / SITUATIONAL),
 * and sequence number (display order).
 *
 * Has one optional InterviewResponse — null until the user answers.
 */
@Entity
@Table(name = "interview_questions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class InterviewQuestion extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "interview_id", nullable = false)
    private Interview interview;

    @Column(name = "question_text", nullable = false, columnDefinition = "TEXT")
    private String questionText;

    /**
     * The ideal answer outline — used by the AI feedback prompt
     * as a reference to evaluate the user's actual answer.
     */
    @Column(name = "expected_answer", columnDefinition = "TEXT")
    private String expectedAnswer;

    @Enumerated(EnumType.STRING)
    @Column(name = "category", nullable = false, length = 30)
    private QuestionCategory category;

    /**
     * 1-based order within the interview session.
     * Questions are displayed in this order in the report.
     */
    @Column(name = "sequence_number", nullable = false)
    private Integer sequenceNumber;

    /**
     * The user's response — null until they answer this question.
     * mappedBy = "question": InterviewResponse owns the FK column.
     * CascadeType.ALL: saving/deleting question cascades to response.
     */
    @OneToOne(mappedBy = "question",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.LAZY)
    private InterviewResponse response;

    public enum QuestionCategory {
        TECHNICAL, BEHAVIOURAL, SITUATIONAL, HR
    }
}